"""Product update

Revision ID: d5e21a9cee5f
Revises: adeb02c6200b
Create Date: 2022-06-06 13:56:40.234979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d5e21a9cee5f"
down_revision = "adeb02c6200b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "created_at")
    # ### end Alembic commands ###
