"""updates

Revision ID: df3711092823
Revises: 6011c5726624
Create Date: 2022-06-09 01:31:36.944375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "df3711092823"
down_revision = "6011c5726624"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=60), nullable=False),
        sa.Column("last_name", sa.String(length=60), nullable=False),
        sa.Column("cpf", sa.String(length=60), nullable=False),
        sa.Column("phone", sa.String(length=60), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profiles_cpf"), "profiles", ["cpf"], unique=True)
    op.create_index(
        op.f("ix_profiles_phone"), "profiles", ["phone"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_profiles_phone"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_cpf"), table_name="profiles")
    op.drop_table("profiles")
    # ### end Alembic commands ###
